const tags = [
    "grass",
    "road sign",
    "pet",
    "los algarrobos",
    "blanket",
    "airedale",
    "sheep",
    "asleep",
    "erlangen",
    "desert",
    "people",
    "swimming",
    "poodle",
    "mountain",
    "lake",
    "nature",
    "pedestrian",
    "toronto",
    "winter",
    "love",
    "united states",
    "light",
    "accessory",
    "street",
    "snow",
    "dr. k. van der auwera",
    "english bull terrier",
    "silhouette",
    "hound",
    "australia",
    "mesa",
    "tachometer",
    "brick",
    "tr\u00e8bes",
    "sierra nevada",
    "maastricht",
    "strap",
    "blue",
    "argentina",
    "floor",
    "apparel",
    "neon",
    "transportation",
    "bench",
    "sunlight",
    "footwear",
    "dechsendorfer weiher",
    "german shepherd",
    "deutschland",
    "dating"
];

export { tags };